### ISSUE TITLE
opam-repo-ci is down

### ISSUE THREAD

**Issue by kit-ty-kate** [ocaml/infrastructure#101]
For the past 8 hours according to https://observe.ci.dev/
![scrn-2024-02-21-23-43-17](https://github.com/ocaml/infrastructure/assets/2611789/4468bec4-a891-43d6-bbb2-5e8f83393dc5)

**Comment by mtelvers** [comment]
`opam-repo-ci` was jammed with 100% CPU utilisation.  No output in the log to indicate any cause.  It has been restarted.
