### ISSUE TITLE
Redirect from v3.ocaml.org to ocaml.org

### ISSUE THREAD

**Issue by smorimoto** [ocaml/infrastructure#102]
The new version is already running on ocaml.org and I think it makes sense to redirect from v3.

**Comment by mtelvers** [comment]
Thank you for your comment.  v3b.ocaml.org, v3.ocaml.org, ocaml.org and www.ocaml.org are all the same machine.  Are you proposing an HTTP 301 redirect on v3/v3b rather than the current DNS based approach?
