### ISSUE TITLE
opam-repository in Docker

### ISSUE THREAD

**Issue by liyishuai** [ocaml/infrastructure#11]
Are there specific reasons to:
1. Use OPAM with a deep clone of `opam-repository` rather than the default https://opam.ocaml.org, and
2. Set `WorkingDir` to `/home/opam/opam-repository` rather than `/home/opam`?

**Comment by liyishuai** [comment]
Background: In https://github.com/coq-community/docker-base/pull/5#issuecomment-596168515 I considered to base Coq images on top of `ocaml/opam2`, but the settings here have confused me.

**Comment by avsm** [comment]
To answer these questions somewhat late: the reason for the deep clone is that the ocaml-ci picks a specific revision to test against, and this requires a full git checkout.  Hope that helps.
