### ISSUE TITLE
Support for OCaml 5.2 in opam-repo-ci

### ISSUE THREAD

**Issue by tmattio** [ocaml/infrastructure#112]
As reported in https://github.com/ocaml/opam-repository/pull/25685. 5.2 is now in beta2.

**Comment by benmandrew** [comment]
Added in https://github.com/ocurrent/opam-repo-ci/pull/294.

**Comment by shonfeder** [comment]
> Added in [ocurrent/opam-repo-ci#294](https://github.com/ocurrent/opam-repo-ci/pull/294).

It sounds like this issue is completed then?

**Comment by benmandrew** [comment]
Yes this can be closed, but I don't have permissions to do so.
