### ISSUE TITLE
opam index seems to be out of date

### ISSUE THREAD

**Issue by mseri** [ocaml/infrastructure#115]
See https://github.com/ocaml/opam-repository/issues/25829
The fix was merged 5 days ago, but it seems it has not propagated to https://opam.ocaml.org/index.tar.gz 

Can you have a look?

**Comment by mtelvers** [comment]
The machine running the deployer was rebooted to install Debian updates.  However, the pipeline defaults to manual processing after a reboot.  I have set the pipeline running now and will update the command line to prevent this from happening again.  I'll leave this issue open until opam has been redeployed and the command line has been updated.

**Comment by mtelvers** [comment]
opam.ocaml.org has now updated.

**Comment by mtelvers** [comment]
`--confirm-auto-release 120` has been added to the command line of the deployer service, meaning that after a service restart, it will resume automatic operation after 2 minutes.
