### ISSUE TITLE
Please, check if IP 195.19.236.234 is banned

### ISSUE THREAD

**Issue by Kakadu** [ocaml/infrastructure#117]
We have issues with downloading from opam.ocaml.org from our network.
TLS session hangs after 'client hello' packet. 
Wget via https doesn't work too. 
Could you check that we are not explicitly banned on your side?

**Comment by mtelvers** [comment]
There is no explicit ban.  Please can you check if you see the same behaviour with opam-4.ocaml.org and opam-5.ocaml.org?

**Comment by KirillSmirnov** [comment]
Hi, I'm Kakadu's colleague.
Other IP addresses owned by our organization are working perfectly, the only one suffering is 195.19.236.234. This address is a NAT address for a number of end-users with various activity and mindset, so this address might get added to  blacklists used by your hosting provider. Is there any way to check this?

**Comment by mtelvers** [comment]
Scaleway reports that there is no issue blocking in place.  Are you still experiencing difficulty?

**Comment by Kakadu** [comment]
Yes.
For now we are going to look for bugs between us. I'm going to reopen this if needed
