### ISSUE TITLE
Can't install "core" because m4 package is missing

### ISSUE THREAD

**Issue by GrahamCampbell** [ocaml/infrastructure#12]
Can m4 be added to the `ocaml/opam2` images?

**Comment by dra27** [comment]
Sorry for the slow reply! The [ocaml/opam2](https://hub.docker.com/r/ocaml/opam2) are deprecated in favour of the [ocaml/opam](https://hub.docker.com/r/ocaml/opam) images maintained by the [base image builder](https://images.ci.ocaml.org).

This was presumably to use `ocamlfind`? `ocamlfind` no longer requires `m4`, so I imagine this is now longer an issue? If it is, please could you open an issue on the base-image builder at https://github.com/ocurrent/docker-base-images/issues?
