### ISSUE TITLE
Please grant me triage or maintainer permissions on this repository

### ISSUE THREAD

**Issue by shonfeder** [ocaml/infrastructure#122]
Hello! I joined Tarides' Infrastructure team about 1 month ago. We need to do a lot of work relating to this repository, but I currently cannot close issues, set assignees, and labels, merge PRs or do much else. I'll need triage perms here at least and maintenance perms would probably be more helpful.

Thank you in advance!

**Comment by shonfeder** [comment]
Thank you very much!

**Comment by punchagan** [comment]
Hello, I'm also on the same team as Shon. I'd also like to have issue triaging permissions on the repo to close solved issues, or assign issues, etc. 

Thank you!
