### ISSUE TITLE
Benchmark: 405 error on Rebuild

### ISSUE THREAD

**Issue by rjbou** [ocaml/infrastructure#134]
When trying to relaunch a failed benchmark job, we have a `405 Not Allowed`.

**Comment by shonfeder** [comment]
I believe @punchagan is investigating this currently. @punchagan please ping me if I can be a help!

**Comment by punchagan** [comment]
From memory the rebuild functionality was never configured in `current-bench`. Missing benchmarks for open PRs are automatically run, when something triggers a GitHub repository scan. 

This would be something nice to enable. I'll look into this tomorrow.

**Comment by punchagan** [comment]
This seems to have broken with our move to [bench.ci.dev](http://bench.ci.dev/). Apologies for the inconvenience, and thanks for notifying us. This should be fixed now.

**Comment by mtelvers** [comment]
Thanks @punchagan
