### ISSUE TITLE
"git" "cat-file " called with extra space in lint job

### ISSUE THREAD

**Issue by mseri** [ocaml/infrastructure#142]
The lint pass started showing a strange error:
```
2024-07-02 15:45.13: Exec: "git" "cat-file " "-e" "5d2717d7e51d35b1da4a5b89d3e60585d5fe8639:packages/async_ssl"
git: 'cat-file ' is not a git command. See 'git --help'.

The most similar command is
	cat-file
```

**Comment by mseri** [comment]
See e.g. https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/a4ad0a49273421b123a224f2a95a9f2beb789797/variant/(lint)

**Comment by shonfeder** [comment]
This is an error introduced in https://github.com/ocurrent/opam-repo-ci/pull/316, for which I am partially responsible. I'm sorry that this made into production!

**Comment by mseri** [comment]
No problem and thanks for the fast fix

**Comment by punchagan** [comment]
Thanks for reporting this, @mseri and for the quick fix, @shonfeder !
