### ISSUE TITLE
Widespread solver timeouts

### ISSUE THREAD

**Issue by mseri** [ocaml/infrastructure#147]
Hi, this is probably not new to you since it has been happening for a while, but it seems that the solver timeout is getting worse. See for example https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/ea1c96487177ade5aaebf46c09829dc8f0d85aad where we have 269 packages whose tests are hitting the solver timeout error.

**Comment by mseri** [comment]
Or the 125 timeout failures here: https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/ade85bbd9960da6240b86f5fea8d35640ac62ec9

**Comment by mtelvers** [comment]
Here's a graph showing the number of jobs which ended in "resolution of the request timed out" for 2024.

![timeouts](https://github.com/user-attachments/assets/1b38fa8f-cd4e-4536-86ea-715e211d75d3)

**Comment by shonfeder** [comment]
We still have some lingering work to do here but this is not longer "widespread", afaik, but only occurring on older opam versions, as discussed on https://github.com/ocurrent/opam-repo-ci/issues/354.

**Comment by mseri** [comment]
Thanks a lot!

**Comment by mseri** [comment]
Timeouts are reappearing. An example in a recent PR: https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/393696e862151646d6f9e8b0e8f4bd159d32b277

**Comment by mtelvers** [comment]
![timeouts](https://github.com/user-attachments/assets/29fc3f70-f2c7-4c28-85c6-accc00fcc1da)
