### ISSUE TITLE
Clear out docker/overlay2 directories on Autumn and Fermat

### ISSUE THREAD

**Issue by punchagan** [ocaml/infrastructure#148]
Errors as in #70 are starting to appear again, which means it is time to clear up the overlay2 directories. 

![image](https://github.com/user-attachments/assets/2289ea1f-148c-45e3-9a57-69ac0999b244)

Due to this maintenance work on Thursday 18th July ‘24 between 0900 and 1000 hrs (UTC), the current-bench benchmarking service will be unavailable.

Thank you for your patience and understanding during this time.

**Comment by punchagan** [comment]
- `autumn`'s disk has been cleared and the service is up and running. 
- The `fermat` worker is still under maintenance.

**Comment by punchagan** [comment]
The `fermat` worker is up and running too.

**Comment by emillon** [comment]
FYI, I'm seeing

> #6 ERROR: failed to prepare sha256:4f328cb4fb73b94a66c9be54296623ad0e689c39cf6529f8edd106d6aa46f524 as 9axxn7i88stoh2t4o23sf6nw6: open /mnt/docker/overlay2/db92ed495b712434df53449e19be3bddc637849dfd04e17e800691176cb545b4/.tmp-committed2982833929: no such file or directory

on https://bench.ci.dev/_pipeline/job/2024-07-18/130118-ocluster-build-d93d70

**Comment by punchagan** [comment]
Thanks for the report. It should now be fixed. 

Clearing out the `overlay2` directory alone, and running a `docker system prune -af` doesn't clear out all the cache references correctly. 

The correct way to clean up disk space for this issue is to: 

1. Stop docker
2. Move the `/var/lib/docker` (or wherever the docker data root lives) directory
3. Start docker and let it create all the required directories
4. Stop docker
5. Copy the `volumes` from the old backed-up directory into the newly created data root.
6. Restart docker
