### ISSUE TITLE
Sandmark runs fail due to Lwt 5.7.0 compilation error

### ISSUE THREAD

**Issue by punchagan** [ocaml/infrastructure#149]
The nightly benchmark runs seem to have failed for a couple of days with [this error](https://github.com/ocaml-bench/sandmark-nightly/commit/0bdd768e8b04e18513ff74886063e6a94791f1cf#diff-3a3dd34f18cea12701126d2fb384dd83098af1911d7b3d7413095767116380bfR471-R491).

**Comment by punchagan** [comment]
It looks like [this change](https://github.com/ocaml/ocaml/commit/36b7209723eb2cf35ba3b87fc37732f04c110464) triggers a failure with building Lwt 5.7.0. 

```
#=== ERROR while compiling lwt.5.7.0 ==========================================#
# context              2.0.7 | linux/x86_64 | ocaml-base-compiler.5.3.0+trunk | git+https://github.com/ocaml/opam-repository.git
# path                 /tmp/sandmark/_opam/5.3.0+trunk/.opam-switch/build/lwt.5.7.0
# command              /tmp/sandmark/_opam/5.3.0+trunk/bin/dune build -p lwt -j 127
# exit-code            1
# env-file             /tmp/sandmark/_opam/log/lwt-2313823-bf2656.env
# output-file          /tmp/sandmark/_opam/log/lwt-2313823-bf2656.out
### output ###
# unix_writev_job.c:36:1: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘{’ token
# [...]
# unix_writev_job.c:42:1: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘{’ token
#    42 | {
#       | ^
# unix_writev_job.c:59:1: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘{’ token
#    59 | {
#       | ^
# In file included from unix_writev_job.c:15:
# lwt_unix.h:46:6: error: old-style parameter declarations in prototyped function definition
#    46 | void lwt_unix_not_available(char const *feature) Noreturn;
#       |      ^~~~~~~~~~~~~~~~~~~~~~
# unix_writev_job.c:83: error: expected ‘{’ at end of input
```

I'm not sure what the right way to fix this would be. Before I try and dig into fixing this, @MisterDA would you have insights on what might be happening here and how to fix this?

**Comment by MisterDA** [comment]
The problem is probably the `Noreturn` at the end of the prototype.
The particular change causing this in ocaml are these points:

> * CAMLnoret must come first in declarations
>
> * Simplify CAMLnoret definition

I've pushed a fix to Lwt: https://github.com/ocsigen/lwt/pull/1022/commits/0d9db31ce2ac9ed258e8f17821d33f7b65a32b25. In the meantime, you could either apply this patch, or pin-depend on my branch at https://github.com/ocsigen/lwt/pull/1022.

**Comment by MisterDA** [comment]
No, it's clear that I've introduced a regression in the definition of `Noreturn`. I'll submit a new patch reverting to the previous definition of this macro.

**Comment by punchagan** [comment]
Thanks for looking into this @MisterDA. One of the things that was confusing for me was not being able to reproduce the failure with the following steps.

```
opam compiler create ocaml:36b7209723eb2cf35ba3b87fc37732f04c110464
eval $(opam env --switch=ocaml-ocaml-36b7209723eb2cf35ba3b87fc37732f04c110464) 
opam install lwt=5.7.0
```

I'm not sure if there's something specifically in the `sandmark` setup that causes this failure to be triggered.

**Comment by punchagan** [comment]
This should now be fixed! Thanks @MisterDA !
