### ISSUE TITLE
Missing `m4` on macos ci builders

### ISSUE THREAD

**Issue by mseri** [ocaml/infrastructure#151]
The failure looks like the following
```
#=== ERROR while compiling conf-m4.1 ==========================================#
# context              2.2.0~rc1 | macos/x86_64 | ocaml-base-compiler.4.14.2 | file:///Users/mac1000/opam-repository
# path                 ~/.opam/4.14.2/.opam-switch/build/conf-m4.1
# command              ~/.opam/opam-init/hooks/sandbox.sh build sh -exc echo | m4
# exit-code            72
# env-file             ~/.opam/log/conf-m4-65784-fec4df.env
# output-file          ~/.opam/log/conf-m4-65784-fec4df.out
### output ###
# + echo
# + m4
# xcode-select: Failed to locate 'm4', and no install could be requested (perhaps no UI is present). Please install manually from 'developer.apple.com'.
```
Seen on https://github.com/ocaml/opam-repository/pull/26309

**Comment by mtelvers** [comment]
There is no rule in `conf-m4` for macOS.  Perhaps we could fix this with https://github.com/ocaml/opam-repository/pull/26339?

**Comment by shonfeder** [comment]
I believe https://github.com/ocaml/opam-repository/pull/26339 shows that this is `conf-m4` and/or opam issue, and not a problem with the infrastructure. Rather, the infrastructure is doing exactly what we want here, and alerting us to the fact that we are not currently configuring this package correctly for macos.

**Comment by shonfeder** [comment]
LMK if I'm mistaken and we should reopen it.
