### ISSUE TITLE
turn on the turbo button on ex-benchmarking machines

### ISSUE THREAD

**Issue by avsm** [ocaml/infrastructure#16]
@sadiqj mentioned the other day that a number of the machines used for benchmarking were configured in their BIOSes to turn off hyperthreading and power throttling and generally made more predictable.

This also makes them slower, so we should undo the changes and go back to BIOS defaults when returning them to the pool.  /cc @mtelvers to check (I think winter is one of these in the inventory).

**Comment by mtelvers** [comment]
Added Ansible role to the worker setup playbook to check for the hyperthreading capability and to fail if it is available but not enabled.

`winter` is still in use by the benchmarking team.
