### ISSUE TITLE
add a mini blog to the infra site

### ISSUE THREAD

**Issue by avsm** [ocaml/infrastructure#17]
Add in a simple Markdown Jekyll blog to the infra.ocaml.org site, so that we can post significant updates here that the OCaml community should be aware of.  These include significant base container upgrades, changes to central CI and so on.  No need for low level operational things like DNS/machine changes, just user-facing things.

**Comment by mtelvers** [comment]
Blog added.  While you excluded operation changes, I've used our impending DNS/machine change as an initial post just so there was something to test with!

**Comment by avsm** [comment]
That was more of a guideline than a rule ;-) s/Ocaml/OCaml btw!
