### ISSUE TITLE
infra.ocaml.org: add dates for blog entries

### ISSUE THREAD

**Issue by avsm** [ocaml/infrastructure#22]
@mtelvers, might you be able to add dates to the front page of blog posts for http://infra.ocaml.org (the 'recent posts' column).  That way they're easy to distinguish from the more wiki-like posts such as the opam.ocaml.org description.

**Comment by mtelvers** [comment]
@avsm, Yes. I have added dates the the blog posts.

**Comment by avsm** [comment]
Thanks @mtelvers! (you can go ahead and close these issues when done, or even easier add a 'Closes #22' to the git commit message and it'll auto close it)
