### ISSUE TITLE
Watch account for Tarides

### ISSUE THREAD

**Issue by Engil** [ocaml/infrastructure#28]
Hello !

Following the announcement [on Discuss](https://discuss.ocaml.org/t/watch-ocaml-org-out-of-beta-and-a-call-for-new-videos/11561) regarding watch.ocaml.org, I open this issue on behalf of the Tarides Tech Talk team to obtain an account in order for us to share with the community the recordings we think are valuable for the community. :-)

Let us know if it is possible for us to obtain an account and what other informations we need to provide.

Thank you very much!

**Comment by avsm** [comment]
Thanks for volunteering to get more videos upload there, glad to have you!  Could I get a sense of how many talks/channels you might need moving forward?  Ideally, these accounts are best if descriptively named, as when you address them in mastodon only the short version will show up.

For example, if its `@bactrian@watch.ocaml.org`, then it'll just be `@bactrian`.  So something like `@tarides@watch.ocaml.org` would work, but might be confused with `@tarides` if you are elsewhere in the Fediverse.  `@tarides_tech` is a bit of a mouthful.    I'm ok with `@tarides` being the uid, but if you have a think about it and let us know, we'll create the account promptly.

Also needs a contact email to create the account with, ideally to an alias so you can redirect it internally to whoever the current contact is.

**Comment by Engil** [comment]
Hey!
Thanks for your answer.

`@tarides` sounds good, on the Fediverse side of things I think at least the instance name (@watch.ocaml.org) makes it somewhat explicit what's the mission of the account, if displayed.

Contact email would be: tech-talks at tarides.com

Thank you again for your prompt response!
Have a great day.

**Comment by avsm** [comment]
Done, and password sent out of band.  Looking forward to seeing some of the tech talks.
