### ISSUE TITLE
opam.ocaml.org build failures are not highlighted adequately

### ISSUE THREAD

**Issue by avsm** [ocaml/infrastructure#3]
Right now the build failures get sent to the opam-commits mailing list, which it appears most people filter. e.g. ocaml/ocaml.org#853 took a few days to spot.

Ideally we would have the cron job failures highlighted somehow, perhaps via an online service that can alert us more reliably when things go wrong (like PagerDuty?).

This issue is to investigate how to improve the state of affairs for opam.ocaml.org to start with, and then the rest of the ocaml.org infrastructure. /cc @altgr

**Comment by AltGr** [comment]
I have no good knowledge of the available tools that would help us here. What are the options ?

**Comment by avsm** [comment]
I think this requires some googling :) Lets update this issue as we investigate services...

**Comment by mtelvers** [comment]
The [new deployment for opam-3](https://deploy.ci.ocaml.org/?repo=ocaml-opam/opam2web&) surfaces failures more clearly; although the firehose for that is not as public as it should be and it would be better to have that displayed on a dashboard on [ocaml.org](http://ocaml.org/)
