### ISSUE TITLE
emelletv signup

### ISSUE THREAD

**Issue by davesnx** [ocaml/infrastructure#34]
Hi ocaml/infrastructure,

I would like to publish some of the videos from emelle.tv to whatch.ocaml.org. I read on https://watch.ocaml.org/about/instance#terms about opening an issue here to create a personal account. I would like to have an emelletv account If that's possible.

Thanks

**Comment by avsm** [comment]
Would be excellent to get the emelletv videos up here! Account create for `davesnx`, one-time password mailed to you (please change), and the channel name is `emelletv`.
