### ISSUE TITLE
container deployment of ocaml.org

### ISSUE THREAD

**Issue by avsm** [ocaml/infrastructure#4]
There were some bad infrastructure failures in Rackspace that led to ocaml.org logs getting lost.  As a backup to the live deployment, I fixed up the Dockerfile and a stateless pure-HTML server container would be useful to rapidly push out ocaml.org updates without depending on a single VM.

**Comment by mtelvers** [comment]
[ocaml.org](http://ocaml.org/) is now deployed as a container
