### ISSUE TITLE
check.ocamllabs.io in ocaml.org

### ISSUE THREAD

**Issue by cuihtlauac** [ocaml/infrastructure#40]
I have a pending PR to add opam package build check results in package documentation https://github.com/ocaml/ocaml.org/pull/977 using https://check.ocamllabs.io

This uses the http rest API at http://check.ocamllabs.io/api/v1/latest/packages which lies outside the ocaml infrastructure. Would it make sense to have it in `ocaml.org` instead?

CC: @tmattio, @kit-ty-kate

**Comment by mtelvers** [comment]
@cuihtlauac I will work with @kit-ty-kate to update this.  The new name is already available: check.ci.ocaml.org

**Comment by mtelvers** [comment]
https://check.ci.ocaml.org now replaces http://check.ocamllabs.io with an HTTP 301 redirect on the old URL.

> Note the change to https from http.

Thanks to @kit-ty-kate
