### ISSUE TITLE
Downsize staging.docs.ci.ocaml.org

### ISSUE THREAD

**Issue by mtelvers** [ocaml/infrastructure#41]
[staging.docs.ci.ocaml.org](https://staging.docs.ci.ocaml.org) is provisioned with 16 x vCPU and 64GB of RAM.  With the recent work done by @tmcgilchrist these requirements could easily be halved to save on the hosting costs.

We still need to retain about the same amount of disk space ~200GB.

No migration plan is needed, the current instance can be deleted, and we will rebuild using the Ansible playbook.

**Comment by avsm** [comment]
Old VM deleted, and new one setup with same disk space and 4xvCPU and 16GB RAM. If thats not sufficient, can upscale. DNS has been updated to 51.158.163.148 for docs-staging.sw.ocaml.org, staging.docs.ocaml.org and staging.docs-data.ocaml.org

**Comment by tmcgilchrist** [comment]
Thanks Anil
