### ISSUE TITLE
staging.docs.ci.ocaml.org inaccessible over SSH

### ISSUE THREAD

**Issue by mtelvers** [ocaml/infrastructure#43]
After initial success with the new [staging.docs.ci.ocaml.org](https://staging.docs.ci.ocaml.org), we can no longer SSH into the machine.  Please can you reset it?

**Comment by avsm** [comment]
Done; probably an OOM.

**Comment by mtelvers** [comment]
Thank you

**Comment by tmcgilchrist** [comment]
[staging.docs.ci.ocaml.org](https://staging.docs.ci.ocaml.org) is back up and running docs builds. Thanks @avsm
