### ISSUE TITLE
x86-bm-b1 disk failure

### ISSUE THREAD

**Issue by mtelvers** [ocaml/infrastructure#44]
Disk `sdb` has failed on `x86-bm-b1`.

```
root@x86-bm-b1:~# lsblk
NAME        MAJ:MIN RM   SIZE RO TYPE  MOUNTPOINTS
sda           8:0    0 953.9G  0 disk  
├─sda1        8:1    0     1M  0 part  
├─sda2        8:2    0   512M  0 part  [SWAP]
├─sda3        8:3    0   600M  0 part  
│ └─md0       9:0    0   599M  0 raid1 
│   └─md0p1 259:0    0   594M  0 part  /boot
└─sda4        8:4    0 952.2G  0 part  
  └─md1       9:1    0 952.1G  0 raid1 
    └─md1p1 259:1    0 952.1G  0 part  /
sdb           8:16   0 953.9G  0 disk  
├─sdb1        8:17   0     1M  0 part  
├─sdb2        8:18   0   512M  0 part  [SWAP]
├─sdb3        8:19   0   600M  0 part  
│ └─md0       9:0    0   599M  0 raid1 
│   └─md0p1 259:0    0   594M  0 part  /boot
└─sdb4        8:20   0 952.2G  0 part  /var/cache/obuilder

```

Error message in `dmesg`

```
[1558841.377823] blk_update_request: I/O error, dev sdb, sector 1052680 op 0x1:(WRITE) flags 0x800 phys_seg 1 prio class 0
[1558841.379214] md: super_written gets error=-5
[1558841.380677] md/raid1:md0: Disk failure on sdb3, disabling device.
                 md/raid1:md0: Operation continuing on 1 devices.
```

**Comment by avsm** [comment]
That didn't survive very long...

**Comment by avsm** [comment]
x86-bm-b1 has been deleted from DNS/Scaleway, and I've provisioned two new x86-bm-c8 and x86-bm-c9 to help with the cluster load.

**Comment by mtelvers** [comment]
@avsm thank you.  I have removed `x86-bm-b1` and added `c8` and `c9`.

I note that `c9` is quite different to `c[1-8] as it has a 8TB spinning disk, whereas the others have 950GB SSD.

* c9 has [TOSHIBA MG08ADA8](https://storage.toshiba.com/enterprise-hdd/enterprise-capacity/mg08d-series)
* c[1-8] have [WDC PC SA530](https://www.westerndigital.com/en-gb/products/internal-drives/pc-sa530-sata-ssd#SDASB8Y-1T00)

**Comment by avsm** [comment]
Looks like it was misprovisioned on the SW side, but while we're here, would that machine be a possible replacement for the Irmin powerpc usage? They just need a lot of disk and no CPU, so could in theory use c9's disk while it serves the cluster at a lower load...

**Comment by mtelvers** [comment]
@avsm Both `pisto` and `prothroe` can now be removed.

**Comment by avsm** [comment]
Thanks @mtelvers!
