### ISSUE TITLE
Can I get access to upload videos?

### ISSUE THREAD

**Issue by jonahbeckford** [ocaml/infrastructure#49]
I'd like to mirror any videos I post to YouTube (ex. https://www.youtube.com/watch?v=OV19_FqAUCw).

Thanks! Jonah

**Comment by avsm** [comment]
Sure! What's your preferred username on watch.ocaml.org?

**Comment by jonahbeckford** [comment]
jonahbeckford@

Thanks!

**Comment by avsm** [comment]
Done! You should be able to 'reset password' with that username to your diskuv email address, and gain access. Enjoy!

**Comment by jonahbeckford** [comment]
I should have tried this out immediately. I tried the reset to jonah +AT diskuv.com (twice) and I have not gotten any emails. It is not flagged as junk either. Will wait for a day to see if the email (if any) is just stuck in a sendmail queue.
