### ISSUE TITLE
Mailing-list for Merlin

### ISSUE THREAD

**Issue by let-def** [ocaml/infrastructure#5]
Merlin mailing-list (barely ever used) is on OCamlforge, which is expected to disappear in the future.
It would be nice to have the mailing-list hosted with the ocaml infrastructure.

Old-url: https://lists.forge.ocamlcore.org/cgi-bin/listinfo/merlin-discuss

**Comment by avsm** [comment]
Do you have any mbox archives you want injected into the new lisrt?  What `<name>@lists.ocaml.org` would you like, and who as admin?

**Comment by let-def** [comment]
Simply merlin@lists.ocaml.org ? And me as admin (frederic.bour @ lakaban.net).

I am trying to get mbox from ocamlforge, but I don't even remember administration password :)...

**Comment by let-def** [comment]
Please find the mbox here: `https://alfred.lakaban.net/~def/merlin-discuss.mbox` (hopefully the right format).

**Comment by avsm** [comment]
I have now created the Merlin mailing list at <merlin@lists.ocaml.org>:

   http://lists.ocaml.org/listinfo/merlin

and injected the archives above:

  http://lists.ocaml.org/pipermail/merlin/

Moderators are @let-def and @gemmag

**Comment by let-def** [comment]
Thank you!
