### ISSUE TITLE
v2.ocaml.org is down

### ISSUE THREAD

**Issue by tmattio** [ocaml/infrastructure#50]
Reported at https://discuss.ocaml.org/t/manual-server-down/12389.

**Comment by tmattio** [comment]
The server is back up and running.

From @mtelvers:

> the host has rebooted ~2 hours ago.  The Docker container has not restarted.

**Comment by mtelvers** [comment]
[v2.ocaml.org](http://v2.ocaml.org/) is a Scaleway virtual machine with a private network address in the 10.0.0.0/8 range allocated by DHCP.  Scaleway powered down the machine for maintenance or hardware failure, and when it restarted, it was issued a different IP address.  Our Docker configuration was bound to the old IP, 10.197.242.33, so the container could not start.  The configuration has been updated to remove the dependency on any specific IP address.
