### ISSUE TITLE
(Re-open): Can I get access to upload videos?

### ISSUE THREAD

**Issue by jonahbeckford** [ocaml/infrastructure#52]
This is a continuation of #49. I don't believe forgotten password emails are going out; I haven't received an email to jonah +AT diskuv.com after doing Reset a few times.

**Comment by avsm** [comment]
thanks -- @mtelvers or I will look into this.

**Comment by mtelvers** [comment]
@avsm, Initial investigation shows that we are sending the messages, but they are being rejected by Jonah's email provider, Microsoft 365.

    550 5.7.511 Access denied, banned sender[163.172.166.101].  To request removal from this list please forward this message to delist@microsoft.com

I have used the portal at https://sender.office.com to try to unblock the IP address but it has not helped.  Often mail servers check the reverse lookup on addresses, and in this case, 163.172.166.101 does not point to watch.ocaml.org.  It's worth asking Scaleway to update it, as that may be the cause.

Please can you set me up with an account on watch.ocaml.org so I can try a non Microsoft provider?

**Comment by avsm** [comment]
Thanks for the detective work, @mtelvers. I've set the reverse DNS appropriately, and created you an `mtelvers` channel. Feel free to also upload videos :-)

@jonahbeckford, I've sent you your password out-of-band to get you unblocked. Thanks for bearing with us while we debug the service!

**Comment by jonahbeckford** [comment]
Thanks!
