### ISSUE TITLE
Github: Install app current-bench on ocaml/odoc

### ISSUE THREAD

**Issue by Julow** [ocaml/infrastructure#56]
Hi!

The benchmark team offered to enroll on Odoc in [current-bench](https://github.com/ocurrent/current-bench), which requires the installation of a Github App:
https://github.com/marketplace/ocaml-benchmarks

Sorry if this is the wrong place to ask for this.

**Comment by avsm** [comment]
ocaml-benchmarks is now activated for ocaml/odoc as well.

**Comment by Julow** [comment]
Thanks!
