### ISSUE TITLE
CI fails on older OCaml versions because of `--version`

### ISSUE THREAD

**Issue by Leonidas-from-XIV** [ocaml/infrastructure#60]
The CI calls `ocaml --version` which is unsupported before 4.03, so 4.02 builds fail with

```
/src: (run (shell "opam exec -- ocaml --version && opam --version"))

/home/opam/.opam/4.02/bin/ocaml: unknown option '--version'.
```

**Comment by benmandrew** [comment]
Fix deployed.

**Comment by Leonidas-from-XIV** [comment]
Can confirm, it works on 4.02 on my other PR: https://ocaml.ci.dev/github/ocaml-community/yojson/commit/89a67a7d4cc6df21a5802ec3277f7fa9d1d1ca66/variant/debian-12-4.02_opam-2.1
