### ISSUE TITLE
Benchmark CI: No space left on device

### ISSUE THREAD

**Issue by rjbou** [ocaml/infrastructure#70]
Current opam jobs are failing because of a no space left error, see [log](http://autumn.ocamllabs.io:8081/job/2023-09-07/163348-ocluster-build-d35d5e#L3947)

**Comment by kit-ty-kate** [comment]
happened again: https://bench.ci.dev/_pipeline/job/2024-07-09/190820-ocluster-build-b5cac3

**Comment by punchagan** [comment]
Thanks for the ping. I've cleared up the drive for now. We've some cron jobs to do it periodically, but looks like we might need to make tweaks to it. I'll look into it.

**Comment by punchagan** [comment]
We cleared out the "leaking" `overlay2` directories to make more space on `fermat` and `autumn`.  See #148
