### ISSUE TITLE
IPv6 Address Changes

### ISSUE THREAD

**Issue by mtelvers** [ocaml/infrastructure#75]
watch.ocaml.org and staging.ocaml.org are unavailable over IPv6 as their addresses have changed.

The entries should be:

* watch.ocaml.org = 2001:bc8:47e4:202::1
* staging.ocaml.org = 2001:bc8:1204:8c10::1

**Comment by avsm** [comment]
Thanks! Did they change unexpectedly from Scaleway? Those should be fixed addresses just like the IPv4 assignments are, so I'll dig in more later...

**Comment by avsm** [comment]
Both records updated.

**Comment by mtelvers** [comment]
Thank you.  The change is unexpected.  I wonder if the addresses changed when the machines are rebooted.  I rebooted them both relatively recently to install Ubuntu updates.  I'll specifically check it next time.
