### ISSUE TITLE
Deploy Plausible to get ocaml.org analytics

### ISSUE THREAD

**Issue by tmattio** [ocaml/infrastructure#79]
As announced on https://discuss.ocaml.org/t/web-analytics-on-ocaml-org/13188, OCaml.org will start using Plausible as a self-hosted service to collect anonymous usage data on the site.

This issue is to track the deployment of the service at plausible.ocaml.org (tentative name).

Plausible provides documentation on how to setup self-hosting at https://plausible.io/docs/self-hosting.

**Comment by shakthimaan** [comment]
We continue to enhance and improve the OCaml.org web pages with content, tutorials, CSS and navigation changes. Before making more enhancements, we would like to observe traction on the web pages to better serve the community and their needs. In this regard, if you can setup a Plausible self-hosted instance for OCaml.org, and provide us with login access, it will be helpful. Thank you!

**Comment by tmattio** [comment]
Plausible is now available at https://plausible.ci.dev/ocaml.org. Thanks @mtelvers!
