### ISSUE TITLE
Cygwin: host a mirror

### ISSUE THREAD

**Issue by avsm** [ocaml/infrastructure#8]
It would be useful to host a mirror of the Cygwin distribution for OCaml CI use that:

- [ ] has a preinstalled version that can be unpacked without running a graphical installer (for use with Windows 10 native containers)
- [ ] controls the versions of packages such that upstream changes can be staged before they hit our CI (and break it, as in https://github.com/ocaml/ocaml/pull/963).

/cc @dra27

**Comment by dra27** [comment]
Cross-referencing https://github.com/ocurrent/docker-base-images/issues/141. I'm not sure keeping this issue here is helpful while this is unplanned - it could perhaps be re-opened if/when work on ocaml-ci (or anything else) has a proposed technical solution to deploy?

**Comment by avsm** [comment]
The Cygwin mirror is a means to an end indeed. Let's reopen when relevant due to docker-base-images needing it.
