### ISSUE TITLE
bump dune version to 3.11?

### ISSUE THREAD

**Issue by Alizter** [ocaml/infrastructure#82]
We need to update the dune lang version in Dune itself to 3.11 in order to start using some feature. However the bench job we have setup is running some commands using dune 3.10 which get stuck when our project version is 3.11. Any chance we can bump this dune version found in the image? Or better yet remove those commands entirely as they aren't really useful for Dune itself?

PR in question:
- https://github.com/ocaml/dune/pull/9212

**Comment by avsm** [comment]
Not sure who the maintainers of the ocurrent-bench are, but this is likely where the change needs to happen. /cc @shakthimaan @samoht
