### ISSUE TITLE
may I have an account for streaming to watch.ocaml.org ?

### ISSUE THREAD

**Issue by yomimono** [ocaml/infrastructure#83]
Hi there! I'm a longtime (~10y) user of OCaml and occasional streamer of OCaml programming content. In the past I've streamed this content on Twitch, but I think it might be a better fit for watch.ocaml.org , if the maintainers are amenable to some less structured OCaml content appearing there. (It seems most content there so far is scripted and edited.)

I'm only interested in streaming ("live" in the PeerTube parlance), so if this kind of content isn't appropriate, please feel free to just close this request rather than allowing access to me.

**Comment by avsm** [comment]
Sorry for taking so long to respond! I've got no objections to streaming live content, but I'm just not sure what the mechanics of it are. Before we do something on the main OCaml instance, would you like to experiment with live streaming on another Peertube instance and we can get familiar with how it works? You are very welcome to use my instance on https://crank.recoil.org, for example, and then we can migrate to Watch.OCaml if there's other interest. @davesnx may also be interested.

**Comment by yomimono** [comment]
Sure, I'm happy to try it out on your instance first. I'll contact you off GitHub to arrange it.

**Comment by shonfeder** [comment]
Hi, @yomimono! Happy to run into you :)

I'm going to close this as stale, but please re-open if this is something you ended up trying and want to move forward with it!
