### ISSUE TITLE
status.ocaml.ci.dev, ocaml.ci.dev and opam.ci.ocaml.org are (were) down

### ISSUE THREAD

**Issue by mtelvers** [ocaml/infrastructure#85]
These services went down overnight due to btrfs volume issues.  Docker has created >500 btrfs sub volumes, which have consumed all the space furthermore, there is a shortage of metadata space.  As there's no space to manoeuvre, I have copied the databases and logs from this machine onto two separate servers, splitting the ci.dev services and the ocaml.org services.

I have updated the DNS for the ci.dev services.

@avsm please can you update the DNS for opam-repo.ci.ocaml.org and opam.ci.ocaml.org.  The new addresses are:

```
A 147.75.199.25
AAAA 2604:1380:45d1:6500::3
```

We can decide in due course whether we leave these services in the new locations or whether we move them back.  Currently, I am still copying the old log files.

**Comment by avsm** [comment]
They were all CNAMEs to opam-repo-ci.sw.ocaml.org, so I updated that for now. I can regroove the Scaleway VM since that old one won't be used at the moment. Did it look like a hardware SSD failure?

**Comment by mtelvers** [comment]
Great.  Thank you.  The root of the issue is the interaction between Docker and BTRFS.  The recommendation is to use Overlayfs.  See https://github.com/moby/moby/issues/27653.

Yes, the Scaleway VM can be removed.  I have documented the incident on the infra [blog](http://infra.ocaml.org/2023/12/04/services-moved.html).
