### ISSUE TITLE
opam repository index is not updating

### ISSUE THREAD

**Issue by mseri** [ocaml/infrastructure#87]
See https://github.com/ocaml/opam-repository/issues/24895

**Comment by mseri** [comment]
Looking at https://opam.ocaml.org/packages/index-date.html the latest package in the index is ocaml 5.1.1~rc1 which was merged 5 days ago

**Comment by mtelvers** [comment]
Yes, I noticed this earlier and restarted the build.  See https://deploy.ci.ocaml.org/job/2023-12-05/125705-ocluster-build-e4354b for the current in progress build log.  The previous build at 23:11 last night timeout.

**Comment by mseri** [comment]
Thanks a lot

**Comment by mtelvers** [comment]
> Looking at https://opam.ocaml.org/packages/index-date.html the latest package in the index is ocaml 5.1.1~rc1 which was merged 5 days ago

That looks right as that there were no commits between Nov 30 and Dec 4.  The commits on Dec 4 at 17:08 caused a rebuild which eventually timed out at 23:11.

**Comment by mtelvers** [comment]
opam.ocaml.org has now updated

**Comment by mseri** [comment]
Thanks a lot!
