### ISSUE TITLE
CI macos workers are broken

### ISSUE THREAD

**Issue by mseri** [ocaml/infrastructure#90]
We seem to consistently see the following failures:

```
Building on i7-worker-04
git-fetch failed with signal SIGBUS
2024-01-10 14:10.25: Job failed: Failed: Build failed
```

```
Building on i7-worker-03
error: 7169 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
git-fetch failed with exit-code 128
```

```
Building on m1-worker-03
error: 1742 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
git-fetch failed with exit-code 128
```

**Comment by mtelvers** [comment]
Thank you for reporting this.  There seems to be a subset of job where this error occurs.  Approximately, 1% of macOS jobs in the last month have ended with a git-fetch failure.  I seem to remember a previous issue where a corrupt git clone was causing this kind of behaviour.  I'll have a look in more detail in the morning on what the common factor is between the jobs.

**Comment by mtelvers** [comment]
The git-fetch cache on all of the macOS workers has been cleared (and the macOS workers have been updated to the latest Homebrew release).  Please let me know if you continue to experience this issue.

**Comment by mseri** [comment]
Thanks!
