### ISSUE TITLE
benchmarks: ocaml/ocaml benchmark build seems broken

### ISSUE THREAD

**Issue by gasche** [ocaml/infrastructure#95]
https://bench.ci.dev/ocaml/ocaml/branch/trunk

currently shows a build failure. It looks like the last working build happened in November 2023.

The [build log of the last failure](https://bench.ci.dev/_pipeline/job/2024-01-26/160341-ocluster-build-e22f3f) ends as follows:

```
Dockerfile:12
--------------------
  10 |     ADD [ "https://api.github.com/repos/ocaml-benching//git/refs/heads/main", ".bench-repo-gitinfo" ]
  11 |     RUN git clone --branch main https://github.com/ocaml-benching/ 
  12 | >>> WORKDIR 
--------------------
ERROR: failed to solve: dockerfile parse error on line 12: WORKDIR requires exactly one argument
docker-build failed with exit-code 1
2024-01-26 16:03.47: Job failed: Failed: Build failed
```

**Comment by avsm** [comment]
Thanks for the report; looks like ocaml-benching is missing an org in the deployment (like https://github.com/tarides/ocaml-benching), causing the corrupt Dockerfile. /cc @punchagan @art-w @samoht

**Comment by punchagan** [comment]
> Thanks for the report; looks like ocaml-benching is missing an org in the deployment (like https://github.com/tarides/ocaml-benching), causing the corrupt Dockerfile. /cc @punchagan @art-w @samoht

Thanks for the report. It was a buggy configuration that caused the issue. I've fixed the configuration and restarted the service. We can close the issue once a new build is available.

**Comment by gasche** [comment]
Thanks for looking at the issue! As of today, the last build reported on https://bench.ci.dev/ocaml/ocaml/branch/trunk is a failed build from January 29th. I don't know if it just takes a few days for the machine to pick up new trunk commits, or if there should have been rebuilds by now that did not happen.

**Comment by punchagan** [comment]
The builds are configured to happen only on Mondays. But, from memory I thought for a failed latest build the new build should get triggered the next time a webhook notification is fired. I'll look into this, and try to get a new run started.

**Comment by punchagan** [comment]
We now have the benchmark runs data.

**Comment by tmattio** [comment]
Thanks a lot @punchagan!
